language: ruby
before_script:
  - psql -c 'create database db_test;' -U postgres
  - psql -c 'create database db_development;' -U postgres
  - psql -c 'create database db_production;' -U postgres
rvm:
  - 2.2.3
services:
  - postgresql